plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/wanggaga/Desktop/销售预测3+9需求汇总原型"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]